// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package profile

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadProfileStacks returns the embedded CollectionSpec for profileStacks.
func loadProfileStacks() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProfileStacksBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load profileStacks: %w", err)
	}

	return spec, err
}

// loadProfileStacksObjects loads profileStacks and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*profileStacksObjects
//	*profileStacksPrograms
//	*profileStacksMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProfileStacksObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProfileStacks()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// profileStacksSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileStacksSpecs struct {
	profileStacksProgramSpecs
	profileStacksMapSpecs
	profileStacksVariableSpecs
}

// profileStacksProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileStacksProgramSpecs struct {
	TpProfileSchedSwitch *ebpf.ProgramSpec `ebpf:"tp_profile_sched_switch"`
}

// profileStacksMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileStacksMapSpecs struct {
	KernProfileStackEvents *ebpf.MapSpec `ebpf:"kern_profile_stack_events"`
	LastSampleNs           *ebpf.MapSpec `ebpf:"last_sample_ns"`
}

// profileStacksVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profileStacksVariableSpecs struct {
}

// profileStacksObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProfileStacksObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileStacksObjects struct {
	profileStacksPrograms
	profileStacksMaps
	profileStacksVariables
}

func (o *profileStacksObjects) Close() error {
	return _ProfileStacksClose(
		&o.profileStacksPrograms,
		&o.profileStacksMaps,
	)
}

// profileStacksMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProfileStacksObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileStacksMaps struct {
	KernProfileStackEvents *ebpf.Map `ebpf:"kern_profile_stack_events"`
	LastSampleNs           *ebpf.Map `ebpf:"last_sample_ns"`
}

func (m *profileStacksMaps) Close() error {
	return _ProfileStacksClose(
		m.KernProfileStackEvents,
		m.LastSampleNs,
	)
}

// profileStacksVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProfileStacksObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileStacksVariables struct {
}

// profileStacksPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProfileStacksObjects or ebpf.CollectionSpec.LoadAndAssign.
type profileStacksPrograms struct {
	TpProfileSchedSwitch *ebpf.Program `ebpf:"tp_profile_sched_switch"`
}

func (p *profileStacksPrograms) Close() error {
	return _ProfileStacksClose(
		p.TpProfileSchedSwitch,
	)
}

func _ProfileStacksClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed profilestacks_arm64_bpfel.o
var _ProfileStacksBytes []byte
