// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dnsRecvPending struct {
	_    structs.HostLayout
	Buff uint64
	Addr uint64
	Kind uint8
	Pad  [7]uint8
}

// loadDns returns the embedded CollectionSpec for dns.
func loadDns() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dns: %w", err)
	}

	return spec, err
}

// loadDnsObjects loads dns and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dnsObjects
//	*dnsPrograms
//	*dnsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDnsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDns()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dnsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsSpecs struct {
	dnsProgramSpecs
	dnsMapSpecs
	dnsVariableSpecs
}

// dnsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsProgramSpecs struct {
	TpSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterRecvmsg  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvmsg"`
	TpSysEnterSendmsg  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendmsg"`
	TpSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendto"`
	TpSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitRecvmsg   *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvmsg"`
}

// dnsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsMapSpecs struct {
	KernDnsEvents *ebpf.MapSpec `ebpf:"kern_dns_events"`
	RecvBufByPid  *ebpf.MapSpec `ebpf:"recv_buf_by_pid"`
}

// dnsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dnsVariableSpecs struct {
}

// dnsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsObjects struct {
	dnsPrograms
	dnsMaps
	dnsVariables
}

func (o *dnsObjects) Close() error {
	return _DnsClose(
		&o.dnsPrograms,
		&o.dnsMaps,
	)
}

// dnsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsMaps struct {
	KernDnsEvents *ebpf.Map `ebpf:"kern_dns_events"`
	RecvBufByPid  *ebpf.Map `ebpf:"recv_buf_by_pid"`
}

func (m *dnsMaps) Close() error {
	return _DnsClose(
		m.KernDnsEvents,
		m.RecvBufByPid,
	)
}

// dnsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsVariables struct {
}

// dnsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDnsObjects or ebpf.CollectionSpec.LoadAndAssign.
type dnsPrograms struct {
	TpSysEnterRecvfrom *ebpf.Program `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterRecvmsg  *ebpf.Program `ebpf:"tp_sys_enter_recvmsg"`
	TpSysEnterSendmsg  *ebpf.Program `ebpf:"tp_sys_enter_sendmsg"`
	TpSysEnterSendto   *ebpf.Program `ebpf:"tp_sys_enter_sendto"`
	TpSysExitRecvfrom  *ebpf.Program `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitRecvmsg   *ebpf.Program `ebpf:"tp_sys_exit_recvmsg"`
}

func (p *dnsPrograms) Close() error {
	return _DnsClose(
		p.TpSysEnterRecvfrom,
		p.TpSysEnterRecvmsg,
		p.TpSysEnterSendmsg,
		p.TpSysEnterSendto,
		p.TpSysExitRecvfrom,
		p.TpSysExitRecvmsg,
	)
}

func _DnsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dns_x86_bpfel.o
var _DnsBytes []byte
