// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type flowsFlowTuple struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

// loadFlows returns the embedded CollectionSpec for flows.
func loadFlows() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FlowsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load flows: %w", err)
	}

	return spec, err
}

// loadFlowsObjects loads flows and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*flowsObjects
//	*flowsPrograms
//	*flowsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFlowsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFlows()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// flowsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowsSpecs struct {
	flowsProgramSpecs
	flowsMapSpecs
	flowsVariableSpecs
}

// flowsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowsProgramSpecs struct {
	TpInetSockSetState *ebpf.ProgramSpec `ebpf:"tp_inet_sock_set_state"`
	TpTcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"tp_tcp_retransmit_skb"`
}

// flowsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowsMapSpecs struct {
	KernFlowEvents *ebpf.MapSpec `ebpf:"kern_flow_events"`
	RetransByTuple *ebpf.MapSpec `ebpf:"retrans_by_tuple"`
	SynSentTs      *ebpf.MapSpec `ebpf:"syn_sent_ts"`
}

// flowsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type flowsVariableSpecs struct {
}

// flowsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFlowsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowsObjects struct {
	flowsPrograms
	flowsMaps
	flowsVariables
}

func (o *flowsObjects) Close() error {
	return _FlowsClose(
		&o.flowsPrograms,
		&o.flowsMaps,
	)
}

// flowsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFlowsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowsMaps struct {
	KernFlowEvents *ebpf.Map `ebpf:"kern_flow_events"`
	RetransByTuple *ebpf.Map `ebpf:"retrans_by_tuple"`
	SynSentTs      *ebpf.Map `ebpf:"syn_sent_ts"`
}

func (m *flowsMaps) Close() error {
	return _FlowsClose(
		m.KernFlowEvents,
		m.RetransByTuple,
		m.SynSentTs,
	)
}

// flowsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFlowsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowsVariables struct {
}

// flowsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFlowsObjects or ebpf.CollectionSpec.LoadAndAssign.
type flowsPrograms struct {
	TpInetSockSetState *ebpf.Program `ebpf:"tp_inet_sock_set_state"`
	TpTcpRetransmitSkb *ebpf.Program `ebpf:"tp_tcp_retransmit_skb"`
}

func (p *flowsPrograms) Close() error {
	return _FlowsClose(
		p.TpInetSockSetState,
		p.TpTcpRetransmitSkb,
	)
}

func _FlowsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed flows_x86_bpfel.o
var _FlowsBytes []byte
