// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type httpRecvPending struct {
	_    structs.HostLayout
	Buff uint64
	Addr uint64
	Kind uint8
	Pad  [7]uint8
}

// loadHttp returns the embedded CollectionSpec for http.
func loadHttp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HttpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load http: %w", err)
	}

	return spec, err
}

// loadHttpObjects loads http and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*httpObjects
//	*httpPrograms
//	*httpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// httpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpSpecs struct {
	httpProgramSpecs
	httpMapSpecs
	httpVariableSpecs
}

// httpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpProgramSpecs struct {
	TpSysEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterRecvmsg  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_recvmsg"`
	TpSysEnterSendmsg  *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendmsg"`
	TpSysEnterSendto   *ebpf.ProgramSpec `ebpf:"tp_sys_enter_sendto"`
	TpSysExitRecvfrom  *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitRecvmsg   *ebpf.ProgramSpec `ebpf:"tp_sys_exit_recvmsg"`
}

// httpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpMapSpecs struct {
	HttpRecvByPid  *ebpf.MapSpec `ebpf:"http_recv_by_pid"`
	KernHttpEvents *ebpf.MapSpec `ebpf:"kern_http_events"`
}

// httpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpVariableSpecs struct {
}

// httpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpObjects struct {
	httpPrograms
	httpMaps
	httpVariables
}

func (o *httpObjects) Close() error {
	return _HttpClose(
		&o.httpPrograms,
		&o.httpMaps,
	)
}

// httpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpMaps struct {
	HttpRecvByPid  *ebpf.Map `ebpf:"http_recv_by_pid"`
	KernHttpEvents *ebpf.Map `ebpf:"kern_http_events"`
}

func (m *httpMaps) Close() error {
	return _HttpClose(
		m.HttpRecvByPid,
		m.KernHttpEvents,
	)
}

// httpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpVariables struct {
}

// httpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpPrograms struct {
	TpSysEnterRecvfrom *ebpf.Program `ebpf:"tp_sys_enter_recvfrom"`
	TpSysEnterRecvmsg  *ebpf.Program `ebpf:"tp_sys_enter_recvmsg"`
	TpSysEnterSendmsg  *ebpf.Program `ebpf:"tp_sys_enter_sendmsg"`
	TpSysEnterSendto   *ebpf.Program `ebpf:"tp_sys_enter_sendto"`
	TpSysExitRecvfrom  *ebpf.Program `ebpf:"tp_sys_exit_recvfrom"`
	TpSysExitRecvmsg   *ebpf.Program `ebpf:"tp_sys_exit_recvmsg"`
}

func (p *httpPrograms) Close() error {
	return _HttpClose(
		p.TpSysEnterRecvfrom,
		p.TpSysEnterRecvmsg,
		p.TpSysEnterSendmsg,
		p.TpSysEnterSendto,
		p.TpSysExitRecvfrom,
		p.TpSysExitRecvmsg,
	)
}

func _HttpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed http_x86_bpfel.o
var _HttpBytes []byte
