apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kernmonitors.kern.io
spec:
  group: kern.io
  names:
    kind: KernMonitor
    listKind: KernMonitorList
    plural: kernmonitors
    singular: kernmonitor
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                  default: kern
                agent:
                  type: object
                  properties:
                    image:
                      type: string
                    mode:
                      type: string
                      enum: [auto, ebpf, proc, hubble]
                    hubbleRelay:
                      type: string
                    imagePullPolicy:
                      type: string
                    port:
                      type: integer
                      format: int32
                  required: [image]
              required: [agent]
            status:
              type: object
              properties:
                phase:
                  type: string
                mode:
                  type: string
                nodesDesired:
                  type: integer
                nodesReady:
                  type: integer
                agentService:
                  type: string
                message:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Nodes
          type: string
          jsonPath: .status.nodesReady
        - name: Mode
          type: string
          jsonPath: .status.mode
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
